// <auto-generated />
using System;
using Bluewater.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bluewater.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241024093221_Add Attendance and Timesheet updates")]
    partial class AddAttendanceandTimesheetupdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Bluewater.Core.AttendanceAggregate.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LateHrs")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LeaveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TimesheetId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnderHrs")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WorkHrs")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TimesheetId");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("Bluewater.Core.ChargingAggregate.Charging", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chargings");
                });

            modelBuilder.Entity("Bluewater.Core.ContributorAggregate.Contributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Contributors");
                });

            modelBuilder.Entity("Bluewater.Core.DepartmentAggregate.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Bluewater.Core.DependentAggregate.Dependent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Dependents");
                });

            modelBuilder.Entity("Bluewater.Core.DivisionAggregate.Division", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("Bluewater.Core.EmployeeAggregate.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BloodType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ChargingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChargingId1")
                        .HasColumnType("TEXT");

                    b.Property<int>("CivilStatus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeeTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Height")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageUrl")
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LevelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LevelId1")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PayId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PayId1")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PositionId1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChargingId");

                    b.HasIndex("ChargingId1");

                    b.HasIndex("EmployeeTypeId");

                    b.HasIndex("LevelId");

                    b.HasIndex("LevelId1");

                    b.HasIndex("PayId");

                    b.HasIndex("PayId1");

                    b.HasIndex("PositionId");

                    b.HasIndex("PositionId1");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Bluewater.Core.EmployeeTypeAggregate.EmployeeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("Bluewater.Core.HolidayAggregate.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRegular")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("Bluewater.Core.LeaveCreditAggregate.LeaveCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultCredits")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCanCarryOver")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLeaveWithPay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaveCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaveDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LeaveCredits");
                });

            modelBuilder.Entity("Bluewater.Core.LevelAggregate.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("Bluewater.Core.PayAggregate.Pay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasicPay")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HDMF_Con")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HDMF_Er")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pays");
                });

            modelBuilder.Entity("Bluewater.Core.PositionAggregate.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Bluewater.Core.ScheduleAggregate.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Bluewater.Core.SectionAggregate.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Approved1Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Approved2Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Approved3Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Bluewater.Core.ShiftAggregate.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BreakHours")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("ShiftBreakEndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("ShiftBreakTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("ShiftEndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("ShiftStartTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("Bluewater.Core.TimesheetAggregate.Timesheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TimeIn1")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeIn1Orig")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeIn2")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeIn2Orig")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeOut1")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeOut1Orig")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeOut2")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeOut2Orig")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Timesheets");
                });

            modelBuilder.Entity("Bluewater.Core.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Credential")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGlobalSupervisor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupervisedGroup")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bluewater.Core.AttendanceAggregate.Attendance", b =>
                {
                    b.HasOne("Bluewater.Core.EmployeeAggregate.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bluewater.Core.ShiftAggregate.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId");

                    b.HasOne("Bluewater.Core.TimesheetAggregate.Timesheet", "Timesheet")
                        .WithMany()
                        .HasForeignKey("TimesheetId");

                    b.Navigation("Employee");

                    b.Navigation("Shift");

                    b.Navigation("Timesheet");
                });

            modelBuilder.Entity("Bluewater.Core.ContributorAggregate.Contributor", b =>
                {
                    b.OwnsOne("Bluewater.Core.ContributorAggregate.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<int>("ContributorId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Extension")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ContributorId");

                            b1.ToTable("Contributors");

                            b1.WithOwner()
                                .HasForeignKey("ContributorId");
                        });

                    b.Navigation("PhoneNumber");
                });

            modelBuilder.Entity("Bluewater.Core.DepartmentAggregate.Department", b =>
                {
                    b.HasOne("Bluewater.Core.DivisionAggregate.Division", "Division")
                        .WithMany("Departments")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("Bluewater.Core.DependentAggregate.Dependent", b =>
                {
                    b.HasOne("Bluewater.Core.EmployeeAggregate.Employee", "Employee")
                        .WithMany("Dependents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Bluewater.Core.EmployeeAggregate.Employee", b =>
                {
                    b.HasOne("Bluewater.Core.ChargingAggregate.Charging", "Charging")
                        .WithMany()
                        .HasForeignKey("ChargingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bluewater.Core.ChargingAggregate.Charging", null)
                        .WithMany("Employees")
                        .HasForeignKey("ChargingId1");

                    b.HasOne("Bluewater.Core.EmployeeTypeAggregate.EmployeeType", null)
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeTypeId");

                    b.HasOne("Bluewater.Core.LevelAggregate.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bluewater.Core.LevelAggregate.Level", null)
                        .WithMany("Employees")
                        .HasForeignKey("LevelId1");

                    b.HasOne("Bluewater.Core.PayAggregate.Pay", "Pay")
                        .WithMany()
                        .HasForeignKey("PayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bluewater.Core.PayAggregate.Pay", null)
                        .WithMany("Employees")
                        .HasForeignKey("PayId1");

                    b.HasOne("Bluewater.Core.PositionAggregate.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bluewater.Core.PositionAggregate.Position", null)
                        .WithMany("Employees")
                        .HasForeignKey("PositionId1");

                    b.HasOne("Bluewater.Core.EmployeeTypeAggregate.EmployeeType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bluewater.Core.UserAggregate.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bluewater.Core.UserAggregate.User", null)
                        .WithMany("Employees")
                        .HasForeignKey("UserId1");

                    b.OwnsOne("Bluewater.Core.EmployeeAggregate.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("TEXT");

                            b1.Property<string>("AddressContact")
                                .HasMaxLength(300)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("EmergencyContact")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("FathersName")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("MobileNoContact")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("MobileNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("MothersMaidenName")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("ProvincialAddress")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("TEXT");

                            b1.Property<string>("RelationshipContact")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("TelNoContact")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("TelNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.HasKey("EmployeeId");

                            b1.HasIndex("Email")
                                .IsUnique();

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("Bluewater.Core.EmployeeAggregate.EducationInfo", "EducationInfo", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CourseGraduated")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<int>("EducationalAttainment")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("UniversityGraduated")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("Bluewater.Core.EmployeeAggregate.EmploymentInfo", "EmploymentInfo", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("BankAccount")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("DateHired")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("DateRegularized")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("DateResigned")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("DateTerminated")
                                .HasColumnType("TEXT");

                            b1.Property<string>("HDMFNo")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<bool>("HasServiceCharge")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("PHICNo")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("SSSNo")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("TINNo")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("Charging");

                    b.Navigation("ContactInfo");

                    b.Navigation("EducationInfo");

                    b.Navigation("EmploymentInfo");

                    b.Navigation("Level");

                    b.Navigation("Pay");

                    b.Navigation("Position");

                    b.Navigation("Type");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bluewater.Core.LeaveCreditAggregate.LeaveCredit", b =>
                {
                    b.HasOne("Bluewater.Core.EmployeeAggregate.Employee", null)
                        .WithMany("LeaveCredits")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("Bluewater.Core.PositionAggregate.Position", b =>
                {
                    b.HasOne("Bluewater.Core.SectionAggregate.Section", "Section")
                        .WithMany("Positions")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Bluewater.Core.ScheduleAggregate.Schedule", b =>
                {
                    b.HasOne("Bluewater.Core.EmployeeAggregate.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bluewater.Core.ShiftAggregate.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Bluewater.Core.SectionAggregate.Section", b =>
                {
                    b.HasOne("Bluewater.Core.DepartmentAggregate.Department", "Department")
                        .WithMany("Sections")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Bluewater.Core.TimesheetAggregate.Timesheet", b =>
                {
                    b.HasOne("Bluewater.Core.EmployeeAggregate.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Bluewater.Core.ChargingAggregate.Charging", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Bluewater.Core.DepartmentAggregate.Department", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Bluewater.Core.DivisionAggregate.Division", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Bluewater.Core.EmployeeAggregate.Employee", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("LeaveCredits");
                });

            modelBuilder.Entity("Bluewater.Core.EmployeeTypeAggregate.EmployeeType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Bluewater.Core.LevelAggregate.Level", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Bluewater.Core.PayAggregate.Pay", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Bluewater.Core.PositionAggregate.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Bluewater.Core.SectionAggregate.Section", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("Bluewater.Core.UserAggregate.User", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
