// <auto-generated />
using System;
using Bluewater.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bluewater.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241222140331_User Account Migration")]
    partial class UserAccountMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Bluewater.Core.AttendanceAggregate.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LateHrs")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LeaveId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NightShiftHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OverbreakHrs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TimesheetId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnderHrs")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WorkHrs")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TimesheetId");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("Bluewater.Core.ChargingAggregate.Charging", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Chargings");
                });

            modelBuilder.Entity("Bluewater.Core.ContributorAggregate.Contributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Contributor");
                });

            modelBuilder.Entity("Bluewater.Core.DepartmentAggregate.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Bluewater.Core.DependentAggregate.Dependent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Dependents");
                });

            modelBuilder.Entity("Bluewater.Core.DivisionAggregate.Division", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("Bluewater.Core.EmployeeAggregate.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BloodType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ChargingId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CivilStatus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Height")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageUrl")
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LevelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PayId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServiceChargeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChargingId");

                    b.HasIndex("LevelId");

                    b.HasIndex("PayId");

                    b.HasIndex("PositionId");

                    b.HasIndex("ServiceChargeId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Bluewater.Core.EmployeeTypeAggregate.EmployeeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("Bluewater.Core.Forms.DeductionAggregate.Deduction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeductionType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MonthlyAmortization")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NoOfMonths")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RemainingBalance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Deductions");
                });

            modelBuilder.Entity("Bluewater.Core.Forms.FailureInOutAggregate.FailureInOut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("FailureInOuts");
                });

            modelBuilder.Entity("Bluewater.Core.Forms.LeaveAggregate.Leave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHalfDay")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LeaveCreditId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("Bluewater.Core.Forms.OtherEarningAggregate.OtherEarning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EarningType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("OtherEarnings");
                });

            modelBuilder.Entity("Bluewater.Core.Forms.OvertimeAggregate.Overtime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApprovedHours")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Overtimes");
                });

            modelBuilder.Entity("Bluewater.Core.Forms.UndertimeAggregate.Undertime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InclusiveTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Undertimes");
                });

            modelBuilder.Entity("Bluewater.Core.HolidayAggregate.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRegular")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("Bluewater.Core.LeaveCreditAggregate.LeaveCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultCredits")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCanCarryOver")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLeaveWithPay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaveCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaveDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LeaveCredits");
                });

            modelBuilder.Entity("Bluewater.Core.LevelAggregate.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("Bluewater.Core.MealCreditAggregate.MealCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MealCredits");
                });

            modelBuilder.Entity("Bluewater.Core.PayAggregate.Pay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasicPay")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cola")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HDMF_Con")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HDMF_Er")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pays");
                });

            modelBuilder.Entity("Bluewater.Core.PayrollAggregate.Payroll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Absences")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AbsencesAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasicPayAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostOfLivingAllowanceAmount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossPayAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LaborHoursIncome")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LaborHrs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Lates")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LatesAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Leaves")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LeavesAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyAllowanceAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NightDiffAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NightDiffHrs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NightDiffOvertimeAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NightDiffOvertimeHrs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NightDiffRegularHolidayAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NightDiffRegularHolidayHrs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NightDiffSpecialHolidayAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NightDiffSpecialHolidayHrs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Overbreak")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OverbreakAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OvertimeAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OvertimeHrs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OvertimeRegularHolidayAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OvertimeRegularHolidayHrs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OvertimeRestDayAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OvertimeRestDayHrs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OvertimeSpecialHolidayAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OvertimeSpecialHolidayHrs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PagibigAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PagibigERAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PhilhealthAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PhilhealthERAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RefundAbsencesAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RefundOvertimeAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RefundUndertimeAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RegularHolidayAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RegularHolidayHrs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RestDayAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RestDayHrs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SSSAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SSSERAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaryUnderpaymentAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpecialHolidayAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpecialHolidayHrs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SvcCharge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxDeductions")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalConstantDeductions")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalLoanDeductions")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Undertime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UndertimeAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnionDues")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Payrolls");
                });

            modelBuilder.Entity("Bluewater.Core.PositionAggregate.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Bluewater.Core.ScheduleAggregate.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Bluewater.Core.SectionAggregate.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Approved1Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Approved2Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Approved3Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Bluewater.Core.ServiceChargeAggregate.ServiceCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServiceCharges");
                });

            modelBuilder.Entity("Bluewater.Core.ShiftAggregate.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BreakHours")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("ShiftBreakEndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("ShiftBreakTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("ShiftEndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("ShiftStartTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("Bluewater.Core.TimesheetAggregate.Timesheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TimeIn1")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeIn1Orig")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeIn2")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeIn2Orig")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeOut1")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeOut1Orig")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeOut2")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeOut2Orig")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Timesheets");
                });

            modelBuilder.Entity("Bluewater.Core.UserAggregate.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Credential")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGlobalSupervisor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupervisedGroup")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Bluewater.Core.AttendanceAggregate.Attendance", b =>
                {
                    b.HasOne("Bluewater.Core.EmployeeAggregate.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bluewater.Core.ShiftAggregate.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId");

                    b.HasOne("Bluewater.Core.TimesheetAggregate.Timesheet", "Timesheet")
                        .WithMany()
                        .HasForeignKey("TimesheetId");

                    b.Navigation("Employee");

                    b.Navigation("Shift");

                    b.Navigation("Timesheet");
                });

            modelBuilder.Entity("Bluewater.Core.ChargingAggregate.Charging", b =>
                {
                    b.HasOne("Bluewater.Core.DepartmentAggregate.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Bluewater.Core.ContributorAggregate.Contributor", b =>
                {
                    b.OwnsOne("Bluewater.Core.ContributorAggregate.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<int>("ContributorId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Extension")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ContributorId");

                            b1.ToTable("Contributor");

                            b1.WithOwner()
                                .HasForeignKey("ContributorId");
                        });

                    b.Navigation("PhoneNumber");
                });

            modelBuilder.Entity("Bluewater.Core.DepartmentAggregate.Department", b =>
                {
                    b.HasOne("Bluewater.Core.DivisionAggregate.Division", "Division")
                        .WithMany("Departments")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("Bluewater.Core.DependentAggregate.Dependent", b =>
                {
                    b.HasOne("Bluewater.Core.EmployeeAggregate.Employee", "Employee")
                        .WithMany("Dependents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Bluewater.Core.EmployeeAggregate.Employee", b =>
                {
                    b.HasOne("Bluewater.Core.ChargingAggregate.Charging", "Charging")
                        .WithMany()
                        .HasForeignKey("ChargingId");

                    b.HasOne("Bluewater.Core.LevelAggregate.Level", "Level")
                        .WithMany("Employees")
                        .HasForeignKey("LevelId");

                    b.HasOne("Bluewater.Core.PayAggregate.Pay", "Pay")
                        .WithMany("Employees")
                        .HasForeignKey("PayId");

                    b.HasOne("Bluewater.Core.PositionAggregate.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId");

                    b.HasOne("Bluewater.Core.ServiceChargeAggregate.ServiceCharge", null)
                        .WithMany("Employees")
                        .HasForeignKey("ServiceChargeId");

                    b.HasOne("Bluewater.Core.EmployeeTypeAggregate.EmployeeType", "Type")
                        .WithMany("Employees")
                        .HasForeignKey("TypeId");

                    b.HasOne("Bluewater.Core.UserAggregate.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.OwnsOne("Bluewater.Core.EmployeeAggregate.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AddressContact")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Email")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EmergencyContact")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FathersName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("MobileNoContact")
                                .HasColumnType("TEXT");

                            b1.Property<string>("MobileNumber")
                                .HasColumnType("TEXT");

                            b1.Property<string>("MothersMaidenName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ProvincialAddress")
                                .HasColumnType("TEXT");

                            b1.Property<string>("RelationshipContact")
                                .HasColumnType("TEXT");

                            b1.Property<string>("TelNoContact")
                                .HasColumnType("TEXT");

                            b1.Property<string>("TelNumber")
                                .HasColumnType("TEXT");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("Bluewater.Core.EmployeeAggregate.EducationInfo", "EducationInfo", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CourseGraduated")
                                .HasColumnType("TEXT");

                            b1.Property<int>("EducationalAttainment")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("UniversityGraduated")
                                .HasColumnType("TEXT");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("Bluewater.Core.EmployeeAggregate.EmploymentInfo", "EmploymentInfo", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("BankAccount")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("DateHired")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("DateRegularized")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("DateResigned")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("DateTerminated")
                                .HasColumnType("TEXT");

                            b1.Property<string>("HDMFNo")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("HasServiceCharge")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("PHICNo")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SSSNo")
                                .HasColumnType("TEXT");

                            b1.Property<string>("TINNo")
                                .HasColumnType("TEXT");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("Charging");

                    b.Navigation("ContactInfo");

                    b.Navigation("EducationInfo");

                    b.Navigation("EmploymentInfo");

                    b.Navigation("Level");

                    b.Navigation("Pay");

                    b.Navigation("Position");

                    b.Navigation("Type");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bluewater.Core.Forms.DeductionAggregate.Deduction", b =>
                {
                    b.HasOne("Bluewater.Core.EmployeeAggregate.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Bluewater.Core.Forms.FailureInOutAggregate.FailureInOut", b =>
                {
                    b.HasOne("Bluewater.Core.EmployeeAggregate.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Bluewater.Core.Forms.LeaveAggregate.Leave", b =>
                {
                    b.HasOne("Bluewater.Core.EmployeeAggregate.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Bluewater.Core.Forms.OtherEarningAggregate.OtherEarning", b =>
                {
                    b.HasOne("Bluewater.Core.EmployeeAggregate.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Bluewater.Core.Forms.OvertimeAggregate.Overtime", b =>
                {
                    b.HasOne("Bluewater.Core.EmployeeAggregate.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Bluewater.Core.Forms.UndertimeAggregate.Undertime", b =>
                {
                    b.HasOne("Bluewater.Core.EmployeeAggregate.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Bluewater.Core.LeaveCreditAggregate.LeaveCredit", b =>
                {
                    b.HasOne("Bluewater.Core.EmployeeAggregate.Employee", null)
                        .WithMany("LeaveCredits")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("Bluewater.Core.PayrollAggregate.Payroll", b =>
                {
                    b.HasOne("Bluewater.Core.EmployeeAggregate.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Bluewater.Core.PositionAggregate.Position", b =>
                {
                    b.HasOne("Bluewater.Core.SectionAggregate.Section", "Section")
                        .WithMany("Positions")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Bluewater.Core.ScheduleAggregate.Schedule", b =>
                {
                    b.HasOne("Bluewater.Core.EmployeeAggregate.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bluewater.Core.ShiftAggregate.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Bluewater.Core.SectionAggregate.Section", b =>
                {
                    b.HasOne("Bluewater.Core.DepartmentAggregate.Department", "Department")
                        .WithMany("Sections")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Bluewater.Core.TimesheetAggregate.Timesheet", b =>
                {
                    b.HasOne("Bluewater.Core.EmployeeAggregate.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bluewater.Core.DepartmentAggregate.Department", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Bluewater.Core.DivisionAggregate.Division", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Bluewater.Core.EmployeeAggregate.Employee", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("LeaveCredits");
                });

            modelBuilder.Entity("Bluewater.Core.EmployeeTypeAggregate.EmployeeType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Bluewater.Core.LevelAggregate.Level", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Bluewater.Core.PayAggregate.Pay", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Bluewater.Core.PositionAggregate.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Bluewater.Core.SectionAggregate.Section", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("Bluewater.Core.ServiceChargeAggregate.ServiceCharge", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
